# npm run build -- ttf::IosevkaCustom

[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

# # JetBrains Mono Style (ss14)
# [buildPlans.IosevkaCustom.variants]
# inherits = "ss14"

# [buildPlans.IosevkaCustom.variants.design]
# brace = "curly-flat-boundary"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.widths.Normal]
shape = 548
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
