# npm run build -- ttf::IosevkaCustom

[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

# # JetBrains Mono Style (ss14)
# [buildPlans.IosevkaCustom.variants]
# inherits = "ss14"

# [buildPlans.IosevkaCustom.variants.design]
# brace = "curly-flat-boundary"

[buildPlans.IosevkaCustom.widths.Normal]
shape = 564
menu = 5
css = "normal"
